In [1]:
import numpy as np
print(np.__version__)

1.19.5


Numpy provides many functions to **create** arrays


In [2]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.98544842 0.92327474]
 [0.32585606 0.4265788 ]]



**Slicing:** In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing.


In [3]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
nums = np.array(nums)     # convert python list to numpy array
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Create a new sub-array
print(nums)  
print(nums.shape) 

[0 1 2 3 4]
[2 3]
[2 3 4]
[0 1]
[0 1 2 3 4]
[0 1 2 3]
[0 1 8 9 4]
(5,)



Let us see some examples of **Matrix** **multiplication**


In [4]:
import time  # import module to calculate execution time


In [5]:
x = np.array([1, 0.01, 0.5, 0.78])
w = np.array([1, 2, 3, -3])
b = 0.5

start_time = time.time()
y = np.dot(w, x) + b  # linear regression
end_time = time.time()
print(y)
print(y.shape)

vec_time = end_time-start_time
print("Execution time with vectorization {} seconds".format(vec_time))

0.6799999999999999
()
Execution time with vectorization 0.00011229515075683594 seconds


The same result can be obtained with a less efficient for loop.

In [6]:
start_time = time.time()
x_n = x.shape[0]
y = 0
for i in range(x_n):
   y += w[i]*x[i] + b
end_time = time.time()

print(y)
print(y.shape)

print("Execution time without vectorization {} seconds".format(end_time-start_time))
print(vec_time/(end_time-start_time))   # print the increase in execution time 
                                        # warning: for small vectors it varies a lot between runs!

2.1799999999999997
()
Execution time without vectorization 0.0002315044403076172 seconds
0.4850669412976313


The matmul function allow to multiply N-Dimensional arrays - the behaviour 



In [7]:
a = np.random.random_sample(size=(5,3))  # generate random matrix with 5 rows and 3 columns
b = np.random.random_sample(size=(3,4))  # generate random matrix with 3 rows and 4 columns

print(a)
print(b)

c = np.matmul(a,b)
print(c)
print(c.shape)     # prints the shape of the resulting matrix, e.g. (5,4)

[[0.95417874 0.28148844 0.96797956]
 [0.50816528 0.80104628 0.35764277]
 [0.60681103 0.93721807 0.32382408]
 [0.28466093 0.97030136 0.69923638]
 [0.38466739 0.85795615 0.73926566]]
[[0.25941203 0.68545706 0.19906189 0.55908273]
 [0.38729626 0.79436536 0.46852769 0.17597811]
 [0.36791031 0.38702915 0.35790668 0.92139   ]]
[[0.71267453 1.25228952 0.6682721  1.47488735]
 [0.57364688 1.12306707 0.60447144 0.75460152]
 [0.63953335 1.28576583 0.67580437 0.8025557 ]
 [0.70689484 1.2365215  0.76153957 0.97417022]
 [0.70405402 1.23132099 0.74313695 1.04719439]]
(5, 4)



What happens if the inner dimensions are not compatible?


In [8]:
print(np.matmul(b, a))

ValueError: ignored

Let us see another example of how a vectorized implementation is more efficient!


In [ ]:
a = np.random.random_sample((5000,))    # generate a large vector

# vectorized calculation
start_time = time.time()
exp_a = np.exp(a)
end_time = time.time()
print("Execution time with vectorization {} seconds".format(end_time-start_time))

start_time = time.time()
x_n = a.shape[0]
exp_a = np.zeros(a.shape)
for i in range(x_n):
   exp_a[i] = np.exp(a[i])
end_time = time.time()
print("Execution time without vectorization {} seconds".format(end_time-start_time))

**Commented exercises**

The solutions included in this notebook compares different solutions for each exercise, including solutions proposed by ML4VMM students in the Academic Years 20-21 and 21-22.






**Exercise 1**


Given the amount of Carbs, Proteins, Fats in 100g of different foods, 
knowing that carbs and proteins provides 4 calories and fats 9 calories,
calculate the % of calories from carbs, proteins and fats for each food


In [16]:
# rows are carbs, proteins, fats
# columns are food, one food per column
grams = np.array([[ 27, 5.8, 41.5, 18.0 ], [ 0.7, 2.5, 8, 4 ],[ 0.2, 0.3, 1.2, 29.5 ]]) 

grams

array([[27. ,  5.8, 41.5, 18. ],
       [ 0.7,  2.5,  8. ,  4. ],
       [ 0.2,  0.3,  1.2, 29.5]])

In [27]:
#insert here the solution
a = [4, 4, 9]
cals_gram = np.array([a])       # create array from list of list  
print(cals_gram.shape)          # verify array has shape (1, 3)
cals_gram = cals_gram.T        # transpose the array
print(cals_gram.shape)          # verify array has shape (3, 1)

# alternative equivalent solutions
# cals_gram = np.array([[4],[4],[9]])  #array of shape (3,1)
                                
cals = grams * cals_gram        # calculate total calories. 
                                # .T transposes the matrix with final shape 3 x 1 
                                # use broadcasting rules between 3 x 4 and 3 x 1 arrays
print(cals)
cals_p = cals / np.sum(cals, axis=0)     # calculates percentages
print(np.sum(cals, axis= 0))    # print the sum of total calories per food
print(cals_p)                   # print the final result

(1, 3)
(3, 1)
[[108.   23.2 166.   72. ]
 [  2.8  10.   32.   16. ]
 [  1.8   2.7  10.8 265.5]]
[112.6  35.9 208.8 353.5]
[[0.95914742 0.64623955 0.79501916 0.20367751]
 [0.02486679 0.27855153 0.1532567  0.04526167]
 [0.01598579 0.07520891 0.05172414 0.75106082]]


**Exercise 2**

Given two 1-D arrays **x** (real values) and **y** (discreet labels), and a constant parameter *m*, calculate the vector **z** so that :

$z_i = \bigg \{ \begin{matrix} \parallel x_i \parallel ^ 2 \text{  if  } y_i =1 \\ \parallel m - x_i \parallel ^ 2 \text{  if  } y_i = 0 \end{matrix}$

This exercise shows how to implement an if statement in vectorized format

In [54]:
x = np.array([0.08444168, 0.5717077,  0.86764178, 0.2427889,  0.44898618, 0.23330771,
 0.14876752, 0.41267104, 0.38951113, 0.60130308])
print(x)
y = np.array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0])
print(y)


[0.08444168 0.5717077  0.86764178 0.2427889  0.44898618 0.23330771
 0.14876752 0.41267104 0.38951113 0.60130308]
[0 0 1 1 0 0 0 1 1 0]


In [55]:
# insert here the solution
m = 0.2
a = x * x                        
b = (m - x) * (m -x)             # broadcasting will expand m to the same size of x

z = y * a + (1 - y) * b          # observe that for any given binary y, only one term is non-zero
                                 # e.g. z will be equal to a if y == 1 and viceversa
print(z)



[0.01335373 0.13816661 0.75280226 0.05894645 0.06199412 0.0011094
 0.00262477 0.17029739 0.15171892 0.16104416]


In [56]:
# alternative (equivalent) solution

z = y * x * x + (1 - y) * (m - x)* (m - x)
print(z)

[0.01335373 0.13816661 0.75280226 0.05894645 0.06199412 0.0011094
 0.00262477 0.17029739 0.15171892 0.16104416]


In [57]:
# alternative (equivalent) solution
z = y * x * x + np.logical_not(y)*(m-x)*(m-x)   #exploit the implicit conversion 1==True, 0==False
                                                # (1-y) is the real-valued equivalent of NOT(y)
print(z)

[0.01335373 0.13816661 0.75280226 0.05894645 0.06199412 0.0011094
 0.00262477 0.17029739 0.15171892 0.16104416]


In [60]:
# alternative solution 
# this solution is correct, but it is less general as it exploits the properties of these particular functions 
# the previous solution is more general
m2 = (1-y) * m              # define m2 = m if y = 0, 0 if y = 1
                            # (m-x)^2 == (x)^2 if m = 0
z = (m2-x)*(m2-x)
print(z)

[0.0071304  0.32684969 0.44574555 0.00183089 0.20158859 0.05443249
 0.02213178 0.04522897 0.03591447 0.36156539]


**Exercise 3**

Given a matrix x of size M by N, where M is the number of samples and N is the number of features, write a vectorized expression to perform min-max scaling:
𝑥′=  (𝑥  − min⁡(𝑥))/(max⁡(𝑥)−min⁡(𝑥))



In [51]:
#  correct solution
m = 50
n = 10
x = np.random.random_sample((m, n))    # generate random sample
print(x.shape)
print(x[0,:])                          # print first feature vector 
# Observation:
# np.min(x, axis=0) is a vector containing the minimum value of each feature
# np.min(x,axis=0) returns an array of size (N,) (one value per feature)
# Recall = the 0 axis is the column axis
x_scaled = (x - np.min(x, axis=0))/(np.max(x, axis=0) - np.min(x, axis=0))  
print(x_scaled.shape)
print(x_scaled[0,:])

print(np.max(x_scaled, axis=0) )     # sanity check: after rescaling the range of each feature should be 0-1
print(np.min(x_scaled, axis=0) )


(50, 10)
[0.51839991 0.51907134 0.5780618  0.2585677  0.07809388 0.63781549
 0.74473466 0.36537659 0.79383214 0.91580234]
(50, 10)
[0.51643032 0.53790504 0.56084653 0.25003354 0.06588717 0.63622134
 0.77734681 0.36700955 0.78768696 0.93770451]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [52]:
#different (BUT NOT EQUIVALENT) solution: sum along the second axis (axis = 1)
# in this vector, each feature vector is rescaled between 0 and 1, e.g.: 
# features with large values are pushed towards 1, features with small values are pushed towards 0
# in the correct solution, each feature is rescaled between 0 and 1 INDEPENDENTLY
np.min(x, axis=1, keepdims=True)
x_scaled = (x - np.min(x, axis=1, keepdims=True))/(np.max(x, axis=1, keepdims=True) - np.min(x, axis=1, keepdims=True))
print(x_scaled.shape)
print(x_scaled[0,:])   # notice how the recaled vector differs from the correct solution


(50, 10)
[0.52560772 0.52640922 0.59682806 0.21543751 0.         0.668158
 0.79579091 0.34293877 0.85440018 1.        ]


**Exercise 4**


Given a 1D array, calculate the average of each consecutive triplet


In [87]:
x = np.array([1, 3, 5, 10, 15, 12, 23, 5, 6, 10, 10, 10])

In [80]:
x_shape = x.shape
if x.shape[0] % 3 != 0:
  print("The lenght of the array must be multiple of 3!")           # alternatively, we could pad the array with 0
else:
  
  no_triplets =  x.shape[0] // 3                 # calculate the number of triplets
  new_shape = (no_triplets , 3)         

  x_reshaped = np.reshape(x, new_shape)          # reshape the array so that each row is a triplet

  

  print(x_reshaped)
  
  avg_x = np.mean(x_reshaped, axis=1)             # calculate the sum of each triplet (row)

  print(avg_x)
  



[[ 1  3  5]
 [10 15 12]
 [23  5  6]
 [10 10 10]]
[ 3.         12.33333333 11.33333333 10.        ]


In [81]:
# alternative (compact) solution

avg_x = np.reshape(x, (x.shape[0] // 3, 3)).mean(axis=1)
print(avg_x)

[ 3.         12.33333333 11.33333333 10.        ]


In [82]:
 # alternative solution
x_reshaped = np.reshape(x, (3, -1))    # if a dimension is unspecified (-1)
                                       # numpy will infer it in order to be compatible with the initial shape
print(x_reshaped)

avg_x = np.mean(x_reshaped, axis=1)             # calculate the sum of each triplet (row)

print(avg_x)

[[ 1  3  5 10]
 [15 12 23  5]
 [ 6 10 10 10]]
[ 4.75 13.75  9.  ]


In [83]:
#alternative solution
x_reshaped= np.array_split(x, x.shape[0] // 3)     # split the array in N subarrays of equal size
print(x_reshaped)

avg_x = np.mean(x_reshaped, axis=1)             # calculate the sum of each triplet (row)

print(avg_x)

[array([1, 3, 5]), array([10, 15, 12]), array([23,  5,  6]), array([10, 10, 10])]
[ 3.         12.33333333 11.33333333 10.        ]


In [94]:
# incorrect solution
# this solution is not generally a good choice as it does not generalize to arbitrary matrix sizes

avg_x = np.array([np.mean(x[0:3]), np.mean(x[3:6]), np.mean(x[6:9]), np.mean(x[9:12])])
print(avg_x)

[ 3.         12.33333333 11.33333333 10.        ]
